### ISSUE TITLE
Window does not close

### ISSUE THREAD

**Issue by loicspace** [JuliaTopOpt/VTKDataIO.jl#1]
Hi,

Thanks putting together this package, I can now visualize 3D spacecraft models in .3ds and it is awesome.
I'm using the function visualize_3ds("mymodel.3ds") but I am not able to close the window. The close button on the window top frame does not do anything and killing the rendering in the REPL -- not that it would be an actual solution -- does not destroy the window either. Only killing Julia closes the window as far as I can tell.

Am I missing something?
Thanks!

Loic

**Comment by mohamed82008** [comment]
I tried it on my side and it seems to be working fine, you close the window and REPL goes back to normal flow. Can you update the package and let me know if you still have the same problem?

**Comment by mohamed82008** [comment]
Could you try it with VTK 7 to see if it is a problem with VTK, or if they changed some of the functions perhaps, or if the problem is with this package?

**Comment by mohamed82008** [comment]
I will try it with a Ubuntu and VTK 8.0 as soon as I can. Does any `visualize` call give this problem, or only `visualize_3ds`?
