### ISSUE TITLE
`trainulate` error in `write_stl`

### ISSUE THREAD

**Issue by yewalenikhil65** [JuliaTopOpt/VTKDataIO.jl#9]
The function `trainulate` seems undefined in line 3 of `write_stl` function

https://github.com/JuliaTopOpt/VTKDataIO.jl/blob/27ea4cfca14f03ef420aa37b73de462504973853/src/stlIO.jl#L3

**Comment by mohamed82008** [comment]
I think it's defined in https://github.com/JuliaTopOpt/VTKDataTypes.jl/blob/master/src/triangulate.jl

**Comment by yewalenikhil65** [comment]
> I think it's defined in https://github.com/JuliaTopOpt/VTKDataTypes.jl/blob/master/src/triangulate.jl

I see.. Then it's just typo error in VTKDataIO.jl

It should be `traingulate` .. And not `trainulate`
